---
- name: Test is wkhtmltopdf installed
  shell: /usr/bin/which wkhtmltopdf
  register: wkhtmltox_installed
  changed_when: no
  failed_when: no
  environment:
    PATH: "${PATH}:{{ wkhtmltox_dir_install }}"

- name: Install dependencies
  package:
    name: "{{ package_dependencies }}"
    state: present

- name: Test desired version is installed
  shell: "wkhtmltopdf --version | grep 'wkhtmltopdf {{ wkhtmltox_version }} (with patched qt)'"
  when: wkhtmltox_installed is defined
  register: wkhtmltox_already_installed
  changed_when: no
  failed_when: no

- name: 'Download package {{wkhtmltox_package_download_url}}'
  get_url:
    url: '{{wkhtmltox_package_download_url}}'
    dest: '/root/{{ wkhtmltox_package }}'
  when: wkhtmltox_installed is defined or wkhtmltox_already_installed is defined

- name: 'Wkhtmltox | Install deb'
  command: gdebi --n '/root/{{ wkhtmltox_package }}'
  when: wkhtmltox_installed is defined or wkhtmltox_already_installed is defined

- name: Create symlink of /usr/local/bin to /usr/bin
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    state: link
  loop:
    - { src: /usr/local/bin/wkhtmltopdf, dest: /usr/bin/wkhtmltopdf }
    - { src: /usr/local/bin/wkhtmltoimage, dest: /usr/bin/wkhtmltoimage }
  when: wkhtmltox_installed is defined or wkhtmltox_already_installed is defined